/* tslint:disable */
/* eslint-disable */
/**
 * JSON Placeholder API
 * JSONPlaceholder is a free online REST API that you can use whenever you need some fake data. It\'s great for tutorials, testing new libraries, sharing code examples, ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

